//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL.WebAPI.EF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yuluhuangEntities : DbContext
    {
        public yuluhuangEntities()
            : base("name=yuluhuangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Collection> collectTable { get; set; }
        public DbSet<Comman> commanTable { get; set; }
        public DbSet<Info> infoTable { get; set; }
        public DbSet<Item> itemTable { get; set; }
        public DbSet<Note> noteTable { get; set; }
        public DbSet<Task> TaskTable { get; set; }
        public DbSet<Theme> themeTable { get; set; }
        public DbSet<User> userTable { get; set; }

        public System.Data.Entity.DbSet<SL.WebAPI.EF.Models.UserRepository> UserRepositories { get; set; }
    }
}
